name: Build
on:
  push:
    branches: main

jobs:
  Build_and_publish_jar:
    runs-on: ubuntu-latest
    name: Build and Publish
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # Set up Java for building Jar
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
      # Set up Maven
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.6.3
      - name: Build War
        run: |
          mvn package
          
      - uses: actions/upload-artifact@v4
        with:
          name: war
          path: ./target/demo.war
